exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

line-length = 88

[lint]
# select = ["E4", "E7", "E9", "F"]
select = [
  "B",      # flake8-bugbear
  "C4",     # Helps you write better list/set/dict comprehensions.
  "E",      # pycodestyle errors
  "FA",     # Verifies files use from __future__ import annotations if a type is used in the module that can be rewritten using PEP 563.
  "F",      # pyflakes
  "G",      # Better usage of built-in logging
  "I",      # isort - Import sorting
  "LOG",    # Checks for issues using the standard library logging module.
  "PL",     # pylint
  "PYI",    # Linting rules for type annotations.
  "Q",      # Linting rules for quites
  "RUF",    # Ruff lint
  "TCH",    # Move type only imports to type-checking condition.
  "TID",    # Helps you write tidier imports.
  "UP",     # pyupgrade
  "W",      # pycodestyle warnings 
  "SIM",    # flake8-simplify
  "UP",     # New python version changes
  "PTH",    # Use pathlib instead of os.path
]

ignore = ["E501"]

